server:
  port: 8081
spring:
  datasource: #db 접속 정보
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    hikari: #hikari 설정 정보
      username: root
      password: root
      maximum-pool-size: 10

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl